"""Tip calculator generated by AutoSpec.

A single pure-function module: no database, network, file I/O, or web server.
All monetary values use Decimal with round-half-up so results are exact and
deterministic.
"""
from __future__ import annotations

from decimal import Decimal, ROUND_HALF_UP


def _round2(value):
    """Round a numeric value to two decimal places using round-half-up.

    Args:
        value: A number (or numeric string/Decimal) to round.

    Returns:
        A Decimal quantized to two decimal places.
    """
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def calculate_tip(bill_total, tip_percentage, number_of_people):
    """Compute the tip, total-with-tip, and per-person split for a bill.

    Args:
        bill_total: The bill amount before tip (0.00 to 999,999,999.99).
        tip_percentage: The tip percentage (0 to 100).
        number_of_people: The number of people splitting the bill; an integer
            greater than or equal to 1.

    Returns:
        A dict with Decimal values under the keys ``tip_amount``,
        ``total_with_tip``, and ``per_person_amount``, each rounded to two
        decimal places using round-half-up.

    Raises:
        ValueError: If ``number_of_people`` is not an integer >= 1, or if
            ``bill_total`` or ``tip_percentage`` is negative. The inputs are
            left unchanged when an error is raised.
    """
    if isinstance(number_of_people, bool) or not isinstance(number_of_people, int):
        raise ValueError(
            "number of people must be an integer greater than or equal to 1"
        )
    if number_of_people < 1:
        raise ValueError(
            "number of people must be an integer greater than or equal to 1"
        )

    bill = Decimal(str(bill_total))
    pct = Decimal(str(tip_percentage))
    if bill < Decimal("0"):
        raise ValueError("bill total is out of the allowed range")
    if pct < Decimal("0"):
        raise ValueError("tip percentage is out of the allowed range")

    tip_amount = _round2(bill * pct / Decimal("100"))
    total_with_tip = _round2(bill + tip_amount)
    per_person_amount = _round2(total_with_tip / Decimal(number_of_people))
    return {
        "tip_amount": tip_amount,
        "total_with_tip": total_with_tip,
        "per_person_amount": per_person_amount,
    }
