"""LLM client layer and deterministic offline fallback.

Agents depend on the ``LLMClient`` protocol, never on a concrete backend. A
``BedrockClient`` stub represents the real AWS Bedrock path; the
``DeterministicFallbackClient`` returns curated, schema-valid responses for the
canonical tip-calculator demo so the pipeline runs fully offline and the live
demo never fails. ``make_client`` selects Bedrock when configured/reachable and
silently falls back otherwise.
"""
from __future__ import annotations

import json
import os
from typing import Optional

try:  # Protocol is available on 3.8+, guard just in case.
    from typing import Protocol
except ImportError:  # pragma: no cover
    Protocol = object  # type: ignore


# ---------------------------------------------------------------------------
# Curated, known-good tip-calculator artifacts (R13, demo resilience).
# ---------------------------------------------------------------------------

# The generated module is written to disk as ``generated_code.py`` so the test
# suite can ``import generated_code``.
TIP_CALCULATOR_MODULE_NAME = "generated_code"

TIP_CALCULATOR_SOURCE = '''"""Tip calculator generated by AutoSpec.

A single pure-function module: no database, network, file I/O, or web server.
All monetary values use Decimal with round-half-up so results are exact and
deterministic.
"""
from __future__ import annotations

from decimal import Decimal, ROUND_HALF_UP


def _round2(value):
    """Round a numeric value to two decimal places using round-half-up.

    Args:
        value: A number (or numeric string/Decimal) to round.

    Returns:
        A Decimal quantized to two decimal places.
    """
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def calculate_tip(bill_total, tip_percentage, number_of_people):
    """Compute the tip, total-with-tip, and per-person split for a bill.

    Args:
        bill_total: The bill amount before tip (0.00 to 999,999,999.99).
        tip_percentage: The tip percentage (0 to 100).
        number_of_people: The number of people splitting the bill; an integer
            greater than or equal to 1.

    Returns:
        A dict with Decimal values under the keys ``tip_amount``,
        ``total_with_tip``, and ``per_person_amount``, each rounded to two
        decimal places using round-half-up.

    Raises:
        ValueError: If ``number_of_people`` is not an integer >= 1, or if
            ``bill_total`` or ``tip_percentage`` is negative. The inputs are
            left unchanged when an error is raised.
    """
    if isinstance(number_of_people, bool) or not isinstance(number_of_people, int):
        raise ValueError(
            "number of people must be an integer greater than or equal to 1"
        )
    if number_of_people < 1:
        raise ValueError(
            "number of people must be an integer greater than or equal to 1"
        )

    bill = Decimal(str(bill_total))
    pct = Decimal(str(tip_percentage))
    if bill < Decimal("0"):
        raise ValueError("bill total is out of the allowed range")
    if pct < Decimal("0"):
        raise ValueError("tip percentage is out of the allowed range")

    tip_amount = _round2(bill * pct / Decimal("100"))
    total_with_tip = _round2(bill + tip_amount)
    per_person_amount = _round2(total_with_tip / Decimal(number_of_people))
    return {
        "tip_amount": tip_amount,
        "total_with_tip": total_with_tip,
        "per_person_amount": per_person_amount,
    }
'''

TIP_CALCULATOR_TESTS = '''"""Generated pytest suite for the tip calculator.

One test per acceptance criterion; each test name encodes the criterion id it
verifies (test_crit_<req>_<crit>_...).
"""
from __future__ import annotations

from decimal import Decimal

import pytest

from generated_code import calculate_tip


def test_crit_1_1_returns_rounded_amounts():
    """Criterion 1.1: valid inputs return tip/total/per-person rounded to 2dp."""
    result = calculate_tip(100.00, 15, 2)
    assert result["tip_amount"] == Decimal("15.00")
    assert result["total_with_tip"] == Decimal("115.00")
    assert result["per_person_amount"] == Decimal("57.50")


def test_crit_1_2_tip_and_total_formula():
    """Criterion 1.2: tip = bill*pct/100 and total = bill + tip."""
    result = calculate_tip(80.00, 25, 1)
    assert result["tip_amount"] == Decimal("20.00")
    assert result["total_with_tip"] == Decimal("100.00")


def test_crit_1_3_per_person_division():
    """Criterion 1.3: per-person = total / people."""
    result = calculate_tip(90.00, 10, 3)
    assert result["per_person_amount"] == Decimal("33.00")


def test_crit_2_1_zero_tip():
    """Criterion 2.1: zero tip yields tip 0.00 and total equal to the bill."""
    result = calculate_tip(50.00, 0, 4)
    assert result["tip_amount"] == Decimal("0.00")
    assert result["total_with_tip"] == Decimal("50.00")


def test_crit_3_1_invalid_people_rejected():
    """Criterion 3.1: number of people < 1 or non-integer is rejected."""
    with pytest.raises(ValueError):
        calculate_tip(50.00, 10, 0)
    with pytest.raises(ValueError):
        calculate_tip(50.00, 10, 2.5)


def test_crit_4_1_invalid_bill_or_pct_rejected():
    """Criterion 4.1: negative bill total or tip percentage is rejected."""
    with pytest.raises(ValueError):
        calculate_tip(-1.00, 10, 2)
    with pytest.raises(ValueError):
        calculate_tip(50.00, -5, 2)
'''

# Curated spec for the tip-calculator demo. Criterion ids here MUST match the
# ids encoded in the generated test names above.
TIP_CALCULATOR_SPEC = {
    "requirements": [
        {
            "number": 1,
            "title": "Compute tip, total, and per-person amounts",
            "criteria": [
                {
                    "id": "1.1",
                    "given": "a valid bill total, tip percentage, and people count",
                    "when": "the tip is calculated",
                    "then": "the tip, total, and per-person amounts are returned rounded to 2 decimals using round-half-up",
                },
                {
                    "id": "1.2",
                    "given": "a bill total and a tip percentage",
                    "when": "the tip is calculated",
                    "then": "the tip equals bill x pct / 100 and the total equals bill + tip",
                },
                {
                    "id": "1.3",
                    "given": "a total with tip and a number of people",
                    "when": "the tip is calculated",
                    "then": "the per-person amount equals the total divided by the number of people",
                },
            ],
        },
        {
            "number": 2,
            "title": "Zero tip handling",
            "criteria": [
                {
                    "id": "2.1",
                    "given": "a tip percentage of 0",
                    "when": "the tip is calculated",
                    "then": "the tip amount is 0.00 and the total equals the bill total",
                }
            ],
        },
        {
            "number": 3,
            "title": "Reject invalid party size",
            "criteria": [
                {
                    "id": "3.1",
                    "given": "a number of people below 1 or not an integer",
                    "when": "the tip is calculated",
                    "then": "the input is rejected with an error and no amounts are returned",
                }
            ],
        },
        {
            "number": 4,
            "title": "Reject invalid bill or percentage",
            "criteria": [
                {
                    "id": "4.1",
                    "given": "a negative bill total or a negative tip percentage",
                    "when": "the tip is calculated",
                    "then": "the input is rejected with an out-of-range error",
                }
            ],
        },
    ],
    "edge_cases": [
        "Tip percentage of exactly 0 yields a zero tip and unchanged total.",
        "Number of people of 0 or a fractional value is rejected.",
        "Negative bill total is rejected as out of range.",
        "Negative tip percentage is rejected as out of range.",
        "Rounding at the half-cent uses round-half-up.",
    ],
}


class BedrockClient:
    """Stub for the AWS Bedrock-backed LLM client.

    The real implementation would call a Bedrock model (e.g. Anthropic Claude).
    This stub raises on use so the factory falls back to the deterministic
    client whenever Bedrock is not actually wired up.
    """

    def __init__(self, region: Optional[str] = None, model_id: Optional[str] = None):
        self.region = region
        self.model_id = model_id

    def complete(self, system: str, prompt: str, schema: Optional[dict] = None) -> str:
        """Raise to signal Bedrock is unavailable in this environment."""
        raise RuntimeError("BedrockClient is a stub; no Bedrock backend configured")


class DeterministicFallbackClient:
    """Returns curated, schema-valid responses for the tip-calculator demo.

    The ``schema`` argument carries a ``kind`` key telling the client which
    artifact to synthesize: "spec", "code", or "tests".
    """

    def complete(self, system: str, prompt: str, schema: Optional[dict] = None) -> str:
        """Return a JSON string for the requested artifact kind.

        Args:
            system: The agent system prompt (ignored by the fallback).
            prompt: The agent prompt (ignored by the fallback).
            schema: A dict with a ``kind`` of "spec", "code", or "tests".

        Returns:
            A JSON-encoded string the calling agent can parse into a model.
        """
        kind = (schema or {}).get("kind")
        if kind == "spec":
            return json.dumps(TIP_CALCULATOR_SPEC)
        if kind == "code":
            return json.dumps(
                {
                    "module_name": TIP_CALCULATOR_MODULE_NAME,
                    "source": TIP_CALCULATOR_SOURCE,
                }
            )
        if kind == "tests":
            criterion_ids = [
                c["id"]
                for req in TIP_CALCULATOR_SPEC["requirements"]
                for c in req["criteria"]
            ]
            return json.dumps(
                {"source": TIP_CALCULATOR_TESTS, "criterion_ids": criterion_ids}
            )
        raise ValueError("DeterministicFallbackClient: unknown request kind {0!r}".format(kind))


def make_client(prefer_bedrock: Optional[bool] = None) -> "object":
    """Select an LLM client, falling back silently to the deterministic one.

    Bedrock is attempted only when explicitly enabled via the
    ``AUTOSPEC_USE_BEDROCK`` environment variable (or ``prefer_bedrock=True``)
    and credentials/region are present. Any failure constructing or probing the
    Bedrock client results in a silent fallback so the demo always runs.

    Args:
        prefer_bedrock: Override for the env-var-based selection.

    Returns:
        An object implementing the ``complete`` method.
    """
    use_bedrock = prefer_bedrock
    if use_bedrock is None:
        use_bedrock = os.environ.get("AUTOSPEC_USE_BEDROCK", "").lower() in (
            "1",
            "true",
            "yes",
        )
    if use_bedrock:
        try:
            region = os.environ.get("AWS_REGION") or os.environ.get("AWS_DEFAULT_REGION")
            client = BedrockClient(region=region)
            # Probe with a trivial call; the stub raises, triggering fallback.
            client.complete("probe", "probe", {"kind": "probe"})
            return client
        except Exception:  # noqa: BLE001 - any Bedrock problem -> fallback
            pass
    return DeterministicFallbackClient()
