"""Deterministic artifact templates for the tip-calculator demo.

The Spec/Build/Test agents are LLM-backed in production, but for a rock-solid
offline demo these curated, schema-valid artifacts guarantee the pipeline always
runs end to end. The first build attempt deliberately omits input validation so
the self-correcting Review -> Build loop has something real to fix on stage.
"""

from __future__ import annotations

from .models import AcceptanceCriterion, Requirement, SpecDocument


def tip_calculator_spec() -> SpecDocument:
    """Return the structured spec the Spec Agent derives from the demo brief."""
    requirements = (
        Requirement(
            number=1,
            title="Compute tip, total, and per-person amounts",
            criteria=(
                AcceptanceCriterion(
                    id="1",
                    given="a bill total, a tip percentage, and a number of people",
                    when="the calculator runs",
                    then="it returns tip, total-with-tip, and per-person, each rounded to 2 decimals",
                ),
            ),
        ),
        Requirement(
            number=2,
            title="Zero-tip handling",
            criteria=(
                AcceptanceCriterion(
                    id="2",
                    given="a tip percentage of 0",
                    when="the calculator runs",
                    then="the tip is 0.00 and the total equals the bill total",
                ),
            ),
        ),
        Requirement(
            number=3,
            title="Even per-person split",
            criteria=(
                AcceptanceCriterion(
                    id="3",
                    given="a total-with-tip and a number of people",
                    when="the calculator runs",
                    then="the per-person amount is the total divided evenly by the people count",
                ),
            ),
        ),
        Requirement(
            number=4,
            title="Reject invalid party size",
            criteria=(
                AcceptanceCriterion(
                    id="4",
                    given="a number of people less than 1 or not an integer",
                    when="the calculator runs",
                    then="it rejects the input and raises a ValueError",
                ),
            ),
        ),
        Requirement(
            number=5,
            title="Reject negative money inputs",
            criteria=(
                AcceptanceCriterion(
                    id="5",
                    given="a negative bill total or a negative tip percentage",
                    when="the calculator runs",
                    then="it rejects the input and raises a ValueError",
                ),
            ),
        ),
    )
    edge_cases = (
        "Tip percentage of exactly 0 (no tip).",
        "Number of people equal to 0 or negative (invalid).",
        "Non-integer number of people (invalid).",
        "Negative bill total or tip percentage (invalid).",
        "Rounding boundaries such as 0.005 (round-half-up).",
    )
    return SpecDocument(requirements=requirements, edge_cases=edge_cases)


# First attempt: intentionally missing the input-validation branches so the
# Review Agent finds real gaps and the loop self-corrects.
BUGGY_SOURCE = '''\
"""Tip calculator (generated by AutoSpec Build Agent)."""

from decimal import Decimal, ROUND_HALF_UP


def _round2(value):
    """Round a numeric value to 2 decimal places using round-half-up."""
    return float(Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def calculate_tip(bill_total, tip_percentage, num_people):
    """Return tip, total-with-tip, and per-person share for a bill."""
    tip = _round2(bill_total * tip_percentage / 100)
    total = _round2(bill_total + tip)
    per_person = _round2(total / num_people)
    return {"tip": tip, "total": total, "per_person": per_person}
'''


# Second attempt: the Build Agent addresses the reported gaps by adding the
# validation the spec requires.
FIXED_SOURCE = '''\
"""Tip calculator (generated by AutoSpec Build Agent)."""

from decimal import Decimal, ROUND_HALF_UP


def _round2(value):
    """Round a numeric value to 2 decimal places using round-half-up."""
    return float(Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def calculate_tip(bill_total, tip_percentage, num_people):
    """Return tip, total-with-tip, and per-person share for a bill.

    Args:
        bill_total: Pre-tip bill amount (must be >= 0).
        tip_percentage: Tip percentage from 0 to 100 (must be >= 0).
        num_people: Number of people splitting the bill (integer >= 1).
    Returns:
        A dict with keys 'tip', 'total', and 'per_person', each rounded to 2 decimals.
    """
    if not isinstance(num_people, int) or num_people < 1:
        raise ValueError("num_people must be an integer >= 1")
    if bill_total < 0 or tip_percentage < 0:
        raise ValueError("bill_total and tip_percentage must be >= 0")
    tip = _round2(bill_total * tip_percentage / 100)
    total = _round2(bill_total + tip)
    per_person = _round2(total / num_people)
    return {"tip": tip, "total": total, "per_person": per_person}
'''


# One test per acceptance criterion. Function name suffix maps to the criterion id.
TEST_SOURCE = '''\
"""Generated test suite (one test per acceptance criterion)."""

import solution


def test_criterion_1():
    # Criterion 1: tip, total, per-person rounded to 2 decimals
    result = solution.calculate_tip(100.0, 10, 2)
    assert result["tip"] == 10.00
    assert result["total"] == 110.00
    assert result["per_person"] == 55.00


def test_criterion_2():
    # Criterion 2: zero tip -> tip 0.00, total == bill
    result = solution.calculate_tip(80.0, 0, 4)
    assert result["tip"] == 0.00
    assert result["total"] == 80.00


def test_criterion_3():
    # Criterion 3: per-person is total split evenly
    result = solution.calculate_tip(50.0, 20, 3)
    assert result["per_person"] == solution._round2(result["total"] / 3)


def test_criterion_4():
    # Criterion 4: invalid party size is rejected with ValueError
    try:
        solution.calculate_tip(100.0, 10, 0)
    except ValueError:
        return
    raise AssertionError("expected ValueError for num_people < 1")


def test_criterion_5():
    # Criterion 5: negative money inputs are rejected with ValueError
    try:
        solution.calculate_tip(-1.0, 10, 2)
    except ValueError:
        return
    raise AssertionError("expected ValueError for negative bill_total")
'''

CRITERION_IDS = ("1", "2", "3", "4", "5")
